-- Modelo persistido segun docs/arquitectura-y-validacion.md:
-- alias conserva la referencia a su asignacion actual; asignacion es el
-- historial con identidad propia (ADR 0002 y ADR 0003).

CREATE TABLE asignacion (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alias_codigo VARCHAR(16) NOT NULL,
    destino      TEXT        NOT NULL,
    creada_en    TIMESTAMPTZ NOT NULL,
    vence_en     TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_asignacion_alias_id UNIQUE (alias_codigo, id)
);

CREATE TABLE alias (
    codigo               VARCHAR(16) PRIMARY KEY,
    asignacion_actual_id BIGINT,
    -- La referencia actual siempre pertenece al mismo alias.
    CONSTRAINT fk_alias_asignacion_actual
        FOREIGN KEY (codigo, asignacion_actual_id)
        REFERENCES asignacion (alias_codigo, id)
);

ALTER TABLE asignacion
    ADD CONSTRAINT fk_asignacion_alias
    FOREIGN KEY (alias_codigo) REFERENCES alias (codigo);

-- Avance persistente de la generacion secuencial de codigos nuevos:
-- una unica fila, bloqueada con SELECT FOR UPDATE en cada reserva.
CREATE TABLE generador_alias (
    id             SMALLINT PRIMARY KEY CHECK (id = 1),
    proximo_indice BIGINT NOT NULL CHECK (proximo_indice >= 0)
);

INSERT INTO generador_alias (id, proximo_indice) VALUES (1, 0);
