-- Esquema del perfil hsqldb: equivalente a db/migration/V1+V2 en dialecto
-- HSQLDB (VARCHAR(8192) en lugar de TEXT, TIMESTAMP en lugar de TIMESTAMPTZ).
-- Flyway 11 ya no soporta HSQLDB, por eso este script corre con
-- spring.sql.init en cada arranque del perfil.
CREATE TABLE IF NOT EXISTS asignacion (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alias_codigo VARCHAR(16) NOT NULL,
    destino      VARCHAR(8192) NOT NULL,
    creada_en    TIMESTAMP NOT NULL,
    vence_en     TIMESTAMP NOT NULL,
    CONSTRAINT uq_asignacion_alias_id UNIQUE (alias_codigo, id)
);

CREATE TABLE IF NOT EXISTS alias (
    codigo               VARCHAR(16) PRIMARY KEY,
    asignacion_actual_id BIGINT,
    -- La referencia actual siempre pertenece al mismo alias.
    CONSTRAINT fk_alias_asignacion_actual
        FOREIGN KEY (codigo, asignacion_actual_id)
        REFERENCES asignacion (alias_codigo, id)
);

-- Ciclo de claves: esta FK solo puede declararse cuando ya existen ambas
-- tablas, y ALTER no admite IF NOT EXISTS. En reinicios el ALTER falla con
-- "constraint already exists" y sql.init.continue-on-error lo omite.
ALTER TABLE asignacion
    ADD CONSTRAINT fk_asignacion_alias
    FOREIGN KEY (alias_codigo) REFERENCES alias (codigo);

-- Avance persistente de la generacion secuencial de codigos nuevos:
-- una unica fila, bloqueada con SELECT FOR UPDATE en cada reserva.
CREATE TABLE IF NOT EXISTS generador_alias (
    id             SMALLINT PRIMARY KEY CHECK (id = 1),
    proximo_indice BIGINT NOT NULL CHECK (proximo_indice >= 0)
);

INSERT INTO generador_alias (id, proximo_indice)
    SELECT 1, 0
    FROM (VALUES (1)) AS v (dummy)
    WHERE NOT EXISTS (SELECT * FROM generador_alias);

CREATE INDEX IF NOT EXISTS ix_asignacion_vence_en ON asignacion (vence_en);
